### ISSUE TITLE
(ptrorch) PS C:\Users\Administrator\Downloads\Compressed\vehicle-counting-1-master> python detect.py --video_path input.mp4 Traceback (most recent call last):   File "detect.py", line 123, in <module>     config = Config(os.path.join('configs',args.config))   File "D:\ProgramData\Anaconda3\envs\ptrorch\lib\ntpath.py", line 117, in join     genericpath._check_arg_types('join', path, *paths)   File "D:\ProgramData\Anac

### ISSUE THREAD

**Issue by byq-luo** [kaylode/vehicle-counting#1]
(ptrorch) PS C:\Users\Administrator\Downloads\Compressed\vehicle-counting-1-master> python detect.py --video_path input.mp4
Traceback (most recent call last):
  File "detect.py", line 123, in <module>
    config = Config(os.path.join('configs',args.config))
  File "D:\ProgramData\Anaconda3\envs\ptrorch\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "D:\ProgramData\Anaconda3\envs\ptrorch\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
(ptrorch) PS C:\Users\Administrator\Downloads\Compressed\vehicle-counting-1-master>

**Comment by kaylode** [comment]
please try this
```
pip install -U pyyaml
```

**Comment by byq-luo** [comment]
I have installed this.发自我的iPhone------------------ Original ------------------From: Kaylode Kieran  <notifications@github.com>Date: Sun,Nov 8,2020 5:43 PMTo: kaylode/vehicle-counting <vehicle-counting@noreply.github.com>Cc: byq-luo <luozb@chd.edu.cn>, Author <author@noreply.github.com>Subject: Re: [kaylode/vehicle-counting] (ptrorch) PSC:\Users\Administrator\Downloads\Compressed\vehicle-counting-1-master> pythondetect.py --video_path input.mp4 Traceback (most recent call last):   File"detect.py", line 123, in <module>     config =Config(os.path.join('configs',args.config))   File"D:\ProgramData\Anaconda3\envs\ptrorch\lib\ntpath.py", line 117, in join    genericpath._check_arg_types('join', path, *paths)   File "D:\ProgramData\Anac(#1)
please try this
pip install -U pyyaml


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kaylode/vehicle-counting/issues/1#issuecomment-723553016",
"url": "https://github.com/kaylode/vehicle-counting/issues/1#issuecomment-723553016",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kaylode** [comment]
> I have installed this.发自我的iPhone------------------ Original ------------------From: Kaylode Kieran <notifications@github.com>Date: Sun,Nov 8,2020 5:43 PMTo: kaylode/vehicle-counting <vehicle-counting@noreply.github.com>Cc: byq-luo <luozb@chd.edu.cn>, Author <author@noreply.github.com>Subject: Re: [kaylode/vehicle-counting] (ptrorch) PSC:\Users\Administrator\Downloads\Compressed\vehicle-counting-1-master> pythondetect.py --video_path input.mp4 Traceback (most recent call last): File"detect.py", line 123, in <module> config =Config(os.path.join('configs',args.config)) File"D:\ProgramData\Anaconda3\envs\ptrorch\lib\ntpath.py", line 117, in join genericpath._check_arg_types('join', path, *paths) File "D:\ProgramData\Anac(#1) please try this pip install -U pyyaml —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#1 (comment)](https://github.com/kaylode/vehicle-counting/issues/1#issuecomment-723553016)", "url": "[#1 (comment)](https://github.com/kaylode/vehicle-counting/issues/1#issuecomment-723553016)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

You must provide a **config file (.yaml)** as written in the command:
```
python detect.py -c=<version of EfficientDet> --config=<path to project config yaml file> --video_path=<path to video .mp4>
```
You can look at my **./configs/aic-hcmc.yaml** for example, to customize on your on dataset
If you use my **trained efficientdet-d2 weight** you can use that **aic-hcmc.yaml** directly by this command;
```
python detect.py -c=2 --config=aic-hcmc.yaml --video_path=input.mp4
```
However, i recommend fine-tuning the detector on your own dataset for better results

**Comment by byq-luo** [comment]
> > I have installed this.发自我的iPhone------------------ Original ------------------From: Kaylode Kieran [notifications@github.com](mailto:notifications@github.com)Date: Sun,Nov 8,2020 5:43 PMTo: kaylode/vehicle-counting [vehicle-counting@noreply.github.com](mailto:vehicle-counting@noreply.github.com)Cc: byq-luo [luozb@chd.edu.cn](mailto:luozb@chd.edu.cn), Author [author@noreply.github.com](mailto:author@noreply.github.com)Subject: Re: [kaylode/vehicle-counting] (ptrorch) PSC:\Users\Administrator\Downloads\Compressed\vehicle-counting-1-master> pythondetect.py --video_path input.mp4 Traceback (most recent call last): File"detect.py", line 123, in  config =Config(os.path.join('configs',args.config)) File"D:\ProgramData\Anaconda3\envs\ptrorch\lib\ntpath.py", line 117, in join genericpath._check_arg_types('join', path, *paths) File "D:\ProgramData\Anac(#1) please try this pip install -U pyyaml —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#1 (comment)](https://github.com/kaylode/vehicle-counting/issues/1#issuecomment-723553016)", "url": "[#1 (comment)](https://github.com/kaylode/vehicle-counting/issues/1#issuecomment-723553016)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
> 
> You must provide a **config file (.yaml)** as written in the command:
> 
> ```
> python detect.py -c=<version of EfficientDet> --config=<path to project config yaml file> --video_path=<path to video .mp4>
> ```
> 
> You can look at my **./configs/aic-hcmc.yaml** for example, to customize on your on dataset
> If you use my **trained efficientdet-d2 weight** you can use that **aic-hcmc.yaml** directly by this command;
> 
> ```
> python detect.py -c=2 --config=aic-hcmc.yaml --video_path=input.mp4
> ```
> 
> However, i recommend fine-tuning the detector on your own dataset for better results

Thank you.
