### ISSUE TITLE
t7 to pb

### ISSUE THREAD

**Issue by mops1112** [kaylode/vehicle-counting#11]
Hi,
would you advise how to convert t7 to pb?

**Comment by kaylode** [comment]
Hey there, can you explain what exactly t7 and pb are? I don't know what those are

**Comment by mops1112** [comment]
i mean torch model "checkpoint/original_ckpt.t7". 
i want to convert it to .pb for using tensorflow

**Comment by kaylode** [comment]
Sorry, I have little knowledge about Tensorflow so I can't help you. I suggest you look into the original [repo](https://github.com/ZQPei/deep_sort_pytorch) of DeepSORT by ZQPei and ask question there.
