### ISSUE TITLE
error in useing different video name 

### ISSUE THREAD

**Issue by VYRION-Ai** [kaylode/vehicle-counting#13]
when i use your video demo , it works well
but if i use different video name ,(i also remember to change the .josn file name) , it gives me this error.
(car_video is the video name).
if i rename my video to cam_04 it works .

`Fusing layers... 
Model Summary: 213 layers, 7020913 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    main(args, config)
  File "run.py", line 30, in main
    pipeline.run()
  File "/content/main/modules/__init__.py", line 34, in run
    self.cam_config.cam[cam_name],
KeyError: 'car_video'`

**Comment by kaylode** [comment]
You need to modify the video name in ```cam_configs.yaml``` as well

**Comment by VYRION-Ai** [comment]
Thank you , it's work .
