### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by VYRION-Ai** [kaylode/vehicle-counting#14]
why this error happened ? 
it happened in some videos. not all videos .
 
`Fusing layers... 
Model Summary: 308 layers, 21065925 parameters, 0 gradients
Adding AutoShape... 
 76% 219/288 [00:08<00:02, 25.41it/s]
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    main(args, config)
  File "run.py", line 30, in main
    pipeline.run()
  File "/content/main/modules/__init__.py", line 67, in run
    track_result = self.tracker.run(ori_img, boxes, labels, scores)
  File "/content/main/modules/track.py", line 40, in run
    bbox_xyxy[:, 2] += bbox_xyxy[:, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

**Comment by kaylode** [comment]
this could be a bug in my code. I suspect that there is a frame in which no vehicle is present, which may cause this error. I will look into it.
