### ISSUE TITLE
Question: Where to find the list of vehicle types?

### ISSUE THREAD

**Issue by urbanzee-admin** [kaylode/vehicle-counting#16]
Thanks for a really fun project to play with. I tried to find the description of the vehicle/object type detected (e.g. motorcycle, car, bus, etc.). I noticed that one of your gifs shows those, but I couldn't find the list not get a similar result. I did look quickly at the original training data, but at least at first glance couldn't find it in there either.

Could you point me in the right direction?

(oops was logged in with the wrong account, oh well)

**Comment by kaylode** [comment]
Actually I didn't use the object names in the code. I only used the class indices which come from the YOLO's checkpoints (originated from the training data). If you want a list showing which classname correspond to which index number, that description is saved within the model's checkpoints by default, along with the model's weights. See ```networks/yolo.py```, you can use ```obj_dict["name"]``` to get the object name. For more information, look into [author's post](https://github.com/ultralytics/yolov5/issues/36)

**Comment by urbanzee-admin** [comment]
Oh brilliant! Thanks for the pointer, and the quick response.
