### ISSUE TITLE
main file

### ISSUE THREAD

**Issue by 123454xiao** [kaylode/vehicle-counting#19]
where is the main file?????

**Comment by kaylode** [comment]
Hi, what do you mean by that ?

**Comment by 123454xiao** [comment]
In the first step,It request me "cd main",
but when I into the code ,there is no file callled "main' in the code ,I do not know Which code should copy? thank you

**Comment by kaylode** [comment]
Well, `cd` is a Linux command for ***changing the current working directory in Linux***. In the colab notebook, I cloned the project and renamed the folder `main`. Therefore `cd main` means to use the the `main` folder as the working directory.
