### ISSUE TITLE
Slow to detect on windows 10? 

### ISSUE THREAD

**Issue by mradamhoward** [kaylode/vehicle-counting#2]
Hi,

I'm not getting the best performance I was expecting. I am running on windows with an i7 4790k and GTX970 and its not utilizing my cpu or gpu when running the detect.py with -c=2 and batch size of 8. I am running it on a long video but I want to know am I missing something regarding performance or is this just the way it is? It's running incredibly slow with 7s/it.

**Comment by kaylode** [comment]
> Hi,
> 
> I'm not getting the best performance I was expecting. I am running on windows with an i7 4790k and GTX970 and its not utilizing my cpu or gpu when running the detect.py with -c=2 and batch size of 8. I am running it on a long video but I want to know am I missing something regarding performance or is this just the way it is? It's running incredibly slow with 7s/it.

Can you tell me what image size you used ?  The efficientdet d2 version was not that slow at the time I was using.
