### ISSUE TITLE
Pretrained-weight with HCMC-AIC ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [kaylode/vehicle-counting#3]
Hello
Thank for your excellent work. Can you give us a pretrained weight with HCMC-AIC dataset ? The link that you provide is die. https://drive.google.com/file/d/1urU0JKQqrI-BNtOCwqLSPr-aue1qWN0U/view?usp=sharing
Thank you a lot !

**Comment by kaylode** [comment]
I am truly sorry that the trained model was accidentally removed sometimes ago. However, I've just updated the AIC-HCMC2020 dataset link. You can train your own model, it converges very fast.

**Comment by hoangkhoiLE** [comment]
Thank you a lot for your contribution !
