### ISSUE TITLE
Request file camera config

### ISSUE THREAD

**Issue by hoangkhoiLE** [kaylode/vehicle-counting#4]
Hello,

I see that in your folder ./vehicle-counting/configs/cam_configs.yaml. There is a file naming 'aic-hcmc2020/zones/zones_movement_paths/cam_01.json'. But in your link of dataset there is not, just images and annotation. Could you please provide the file json with the zone movement ?

Best regard

**Comment by kaylode** [comment]
I've updated the testset link [here](https://drive.google.com/drive/folders/1Qn5IZBgbaUwqAdhkOdKp969K_4aETl8Y?usp=sharing).
