### ISSUE TITLE
pth files 

### ISSUE THREAD

**Issue by gkomix88** [kaylode/vehicle-counting#5]
Hi,

I would like to run your program. However, I m unable to download the pre-trained pth files for testing.
Do you still keep the model files? Possible to share the link to download?

Thanks.

**Comment by kaylode** [comment]
> Hi,
> 
> I would like to run your program. However, I m unable to download the pre-trained pth files for testing.
> Do you still keep the model files? Possible to share the link to download?
> 
> Thanks.

I'm very sorry, I have just lost all trained checkpoints recently. The only available left are pretrained checkpoints on COCO. You can use these to run the program, the performance of these checkpoints is acceptable. These checkpoints will be loaded by default if no arguments are passed in, you can look into the run.py for the comment lines.
