### ISSUE TITLE
A problem has occurred. Why is this?

### ISSUE THREAD

**Issue by giantdrone** [kaylode/vehicle-counting#9]
I did everything in order, but I got an error.
Do you know what the problem is?

(py38) C:\coding\DeepSORT_YOLOv5_Pytorch-master>python main.py --cam 0 --display
Namespace(agnostic_nms=False, augment=False, cam=0, classes=[0], conf_thres=0.5, config_deepsort='./configs/deep_sort.yaml', device='', display=True, display_height=600, display_width=800, fourcc='mp4v', frame_interval=2, img_size=640, input_path='input_480.mp4', iou_thres=0.5, save_path='output/', save_txt='output/predict/', weights='yolov5/weights/yolov5s.pt')
Initialize DeepSORT & YOLO-V5
Using CPU

Using webcam 0
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    with VideoTracker(args) as vdo_trk:
  File "main.py", line 53, in __init__
    cfg.merge_from_file(args.config_deepsort)
  File "C:\coding\DeepSORT_YOLOv5_Pytorch-master\utils_ds\parser.py", line 23, in merge_from_file
    self.update(yaml.load(fo.read()))
TypeError: load() missing 1 required positional argument: 'Loader'
[ WARN:0] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by kaylode** [comment]
Hello there,

> self.update(yaml.load(fo.read())) 
TypeError: load() missing 1 required positional argument: 'Loader'

this could be an error due to python library ```pyyaml``` version
have you tried installing all the depencies by running ```pip install -r requirements.txt``` ?

**Comment by giantdrone** [comment]
![image](https://user-images.githubusercontent.com/52200850/142578931-81ec461f-1dea-4605-893e-9b24925b2024.png)
Yes. I have already installed it.
Requirement already satisfied: PyYAML>=5.3 in c:\users\maste\anaconda3\envs\py38\lib\site-packages (from -r requirements.txt (line 9)) (6.0)
